import { AiFillStar } from 'react-icons/ai';

const data = [
  {
    id: 1,
    img: 'https://m.media-amazon.com/images/I/61IlNk21I0L._SY500_.jpg',
    title: 'Nike Air Monarch IV',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'white',
    category: 'sneakers',
  },
  {
    id: 2,
    img: 'https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg',
    title: 'Nike Air Vapormax Plus',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'red',
    category: 'sneakers',
  },
  {
    id: 3,
    img: 'https://m.media-amazon.com/images/I/51+g7Vr9YrL._AC_UL320_.jpg',
    title: 'Nike Waffle One Sneaker',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'White',
    category: 'sneakers',
  },
  {
    id: 4,
    img: 'https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg',
    title: 'Nike Running Shoe',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Adidas',
    color: 'black',
    category: 'sneakers',
  },
  {
    id: 5,
    img: 'https://m.media-amazon.com/images/I/51vxFFluJ-L._AC_UL320_.jpg',
    title: 'Flat Slip On Pumps',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Vans',
    color: 'green',
    category: 'flats',
  },
  {
    id: 6,
    img: 'https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg',
    title: 'Knit Ballet Flat',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Adidas',
    color: 'black',
    category: 'flats',
  },
  {
    id: 7,
    img: 'https://m.media-amazon.com/images/I/61c+JnFSKqL._AC_UL320_.jpg',
    title: 'Loafer Flats',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Vans',
    color: 'white',
    category: 'flats',
  },
  {
    id: 8,
    img: 'https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg',
    title: 'Nike Zoom Freak',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'green',
    category: 'sneakers',
  },
  {
    id: 9,
    img: 'https://m.media-amazon.com/images/I/615PyicXonL._AC_UL320_.jpg',
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Adidas',
    color: 'blue',
    category: 'sneakers',
  },
  {
    id: 10,
    img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'PUMA BLACK-OCE',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '9999',
    company: 'Puma',
    color: 'green',
    category: 'sneakers',
  },
  {
    id: 11,
    img: 'https://m.media-amazon.com/images/I/51diUIFYr9L._AC_UL320_.jpg',
    title: 'Pacer Future Sneaker',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Puma',
    color: 'red',
    category: 'sneakers',
  },
  {
    id: 12,
    img: 'https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg',
    title: 'Unisex-Adult Super',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '9999',
    company: 'Puma',
    color: 'black',
    category: 'sneakers',
  },
  {
    id: 13,
    img: 'https://m.media-amazon.com/images/I/61g0hpUI9YL._AC_UL320_.jpg',
    title: 'Roma Basic Sneaker',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Puma',
    color: 'white',
    category: 'sneakers',
  },
  {
    id: 14,
    img: 'https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg',
    title: 'Pacer Future Doubleknit',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '9999',
    company: 'Puma',
    color: 'black',
    category: 'sneakers',
  },
  {
    id: 15,
    img: 'https://m.media-amazon.com/images/I/610VYwnYdCL._AC_UL320_.jpg',
    title: 'Fusion Evo Golf Shoe',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Puma',
    color: 'green',
    category: 'sneakers',
  },
  {
    id: 16,
    img: 'https://m.media-amazon.com/images/I/61epmmBQ48L._SX695_.jpg',
    title: 'Grip Fit Slip Ons',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Vans',
    color: 'red',
    category: 'sandals',
  },
  {
    id: 17,
    img: 'https://m.media-amazon.com/images/I/51nOuY8reOL._AC_UL320_.jpg',
    title: 'Low-Top Trainers',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Vans',
    color: 'white',
    category: 'sandals',
  },
  {
    id: 18,
    img: 'https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg',
    title: 'Vans Unisex Low-Top',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Vans',
    color: 'blue',
    category: 'sandals',
  },
  {
    id: 19,
    img: 'https://m.media-amazon.com/images/I/61NbyDD-pZL._AC_UL320_.jpg',
    title: 'Classic Bandana Sneakers',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'black',
    category: 'sandals',
  },
  {
    id: 20,
    img: 'https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg',
    title: 'Chunky High Heel',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Vans',
    color: 'black',
    category: 'heels',
  },
  {
    id: 21,
    img: 'https://m.media-amazon.com/images/I/71rmoT-LhXL._AC_UL320_.jpg',
    title: 'Slip On Stiletto High Heel',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Puma',
    color: 'black',
    category: 'heels',
  },
  {
    id: 22,
    img: 'https://m.media-amazon.com/images/I/71tFQjdiQ2L._SY695_.jpg',
    title: "Women's Fashion Sandals",
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '9999',
    company: 'Nike',
    color: 'red',
    category: 'heels',
  },
  {
    id: 23,
    img: 'https://m.media-amazon.com/images/I/417kGcuN4zL._AC_UL320_.jpg',
    title: 'Nike Air Vapormax Plus',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'red',
    category: 'sneakers',
  },
  {
    id: 24,
    img: 'https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg',
    title: 'Low Mid Block Heels',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Nike',
    color: 'black',
    category: 'heels',
  },
  {
    id: 29,
    img: 'https://m.media-amazon.com/images/I/51PnX2wF6uL._AC_UL320_.jpg',
    title: 'Puma RS-X Bold',
    star: <AiFillStar className="rating-star" />,
    reviews: '(145 reviews)',
    prevPrice: '₹18999',
    newPrice: '17000',
    company: 'Puma',
    color: 'black',
    category: 'sneakers',
  },
  {
    id: 26,
    img: 'https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg',
    title: 'Amore Fashion Stilettos',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹17000',
    newPrice: '14999',
    company: 'Adidas',
    color: 'white',
    category: 'heels',
  },
  {
    id: 30,
    img: 'https://m.media-amazon.com/images/I/51POw2TfOfL._AC_UL320_.jpg',
    title: 'Puma Future Rider',
    star: <AiFillStar className="rating-star" />,
    reviews: '(132 reviews)',
    prevPrice: '₹18500',
    newPrice: '17000',
    company: 'Puma',
    color: 'white',
    category: 'sneakers',
  },
  {
    id: 28,
    img: 'https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg',
    title: 'Wedding Prom Bridal',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 reviews)',
    prevPrice: '₹11499',
    newPrice: '4999',
    company: 'Adidas',
    color: 'black',
    category: 'heels',
  },
  {
    id: 31,
    img: 'https://m.media-amazon.com/images/I/51FTUNbD21L._AC_UL320_.jpg',
    title: 'Puma Smash V2',
    star: <AiFillStar className="rating-star" />,
    reviews: '(128 reviews)',
    prevPrice: '₹17999',
    newPrice: '17000',
    company: 'Puma',
    color: 'red',
    category: 'sneakers',
  },
  {
    id: 32,
    img: 'https://m.media-amazon.com/images/I/81xADhyCBtL._AC_UL320_.jpg',
    title: 'Puma Carina L',
    star: <AiFillStar className="rating-star" />,
    reviews: '(115 reviews)',
    prevPrice: '₹17500',
    newPrice: '17000',
    company: 'Puma',
    color: 'black',
    category: 'heels',
  },
  {
    id: 33,
    img: 'https://m.media-amazon.com/images/I/51oZDF7rbpL._AC_UL320_.jpg',
    title: 'Puma Mayze',
    star: <AiFillStar className="rating-star" />,
    reviews: '(121 reviews)',
    prevPrice: '₹18000',
    newPrice: '17000',
    company: 'Puma',
    color: 'white',
    category: 'sandals',
  },
];

export default data;
